GEMINI_API_KEY = "AIzaSyCafgUt1sTxW71sbdy2EDFLu4_s1qLST98"
NEWS_API_KEY = "df33528debc248b3b3a270e6c2d3b803"
SERPAPI_API_KEY = "f11791b41015eb8a5e82e09680cf190a0c26a4ba9026094cdfebeccd5db314e7"
MONGO_URI = "mongodb+srv://amulyakh10:dHvP36UwEUkHDHUp@cluster0.nafioat.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Auth0 Credentials
AUTH0_CLIENT_ID = "rbp5MJwEvmlKIhq3tcL9mseVCLpjhSIv"
AUTH0_CLIENT_SECRET = "FUe9-OKNl7g2fH48q910d-HAdpzOMIahP14wT1xP8ZOak71ZSjcWyBO580xJAcwM"
AUTH0_DOMAIN = "dev-at88sl20oncfi7x4.us.auth0.com"