GEMINI_API_KEY = "AIzaSyAh6PAR4p89SDKBXosZrbkudn_lIrkZgck"
NEWS_API_KEY = "df33528debc248b3b3a270e6c2d3b803"
SERPAPI_API_KEY = "f11791b41015eb8a5e82e09680cf190a0c26a4ba9026094cdfebeccd5db314e7"
MONGO_URI = "mongodb+srv://amulyakh10:01wq4VZHIiLkpequ@cluster0.nafioat.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
WEATHER_API_KEY = "78c1e11aacb84f4f85241505252707"

# Auth0 Credentials
AUTH0_CLIENT_ID = "rbp5MJwEvmlKIhq3tcL9mseVCLpjhSIv"
AUTH0_CLIENT_SECRET = "lYCHZ8JPfDE6OBj4m4ApXSo8C1PL7H34aJy5L_h5p-qycGrTrn3vhVpB2DA9ozi0"
AUTH0_DOMAIN = "dev-at88sl20oncfi7x4.us.auth0.com"